# compile-const.awk: compile consts file to a header file
# Copyright (C) 2015, Haldean Brown
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

$0 ~ /^[^-]/ {
        # Not all awks have 64-bit numbers available, so we do this in two goes,
        # requiring only 32 bits from each of our accumulators
        acc1 = 0
        for (i = 1; i <= 4; i++) {
                c = substr($1, i, 1)
                acc1 = or(lshift(acc1, 8), ascii[c])
        }
        acc2 = 0
        for (i = 5; i <= 8; i++) {
                c = substr($1, i, 1)
                acc2 = or(lshift(acc2, 8), ascii[c])
        }
        print "#define " sprintf("% 24s", $2) " " sprintf("0x%X%X", acc1, acc2)
}

BEGIN {
        FS="."
        PREC=64
        for (i = 0; i < 128; i++) {
                t = sprintf("%c", i);
                ascii[t] = i;
        }
        print \
"/*\n" \
"const.h: autogenerated constants\n" \
"Copyright (C) 2015, Haldean Brown\n" \
"\n" \
"This program is free software; you can redistribute it and/or modify\n" \
"it under the terms of the GNU General Public License as published by\n" \
"the Free Software Foundation; either version 2 of the License, or\n" \
"(at your option) any later version.\n" \
"\n" \
"This program is distributed in the hope that it will be useful,\n" \
"but WITHOUT ANY WARRANTY; without even the implied warranty of\n" \
"MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n" \
"GNU General Public License for more details.\n" \
"\n" \
"You should have received a copy of the GNU General Public License along\n" \
"with this program; if not, write to the Free Software Foundation, Inc.,\n" \
"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.\n" \
"\n" \
"######################################################################\n" \
"                       DO NOT CHANGE THIS FILE\n" \
"######################################################################\n" \
"\n" \
"It was autogenerated from res/const.txt by res/compile-const.awk. Change\n" \
"one of those instead.\n" \
"*/\n"
}
